import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
	vue3Version: [
		"vue-3-version/introduction",
		{
			type: "category",
			label: "Get started",
			collapsed: false,
			items: [
				"vue-3-version/guide/introduction",
				"vue-3-version/guide/install-function",
				"vue-3-version/guide/basic-usage/dynamic-load",
				"vue-3-version/guide/basic-usage/region-and-language",
				"vue-3-version/guide/basic-usage/accessing-google-maps-api",
			],
		},
		{
			type: "category",
			label: "Use components",
			collapsed: false,
			items: [
				"vue-3-version/guide/components/map",
				"vue-3-version/guide/basic-usage/map-reference",
				"vue-3-version/guide/components/marker",
				"vue-3-version/guide/components/info-window",
				"vue-3-version/guide/components/circle",
				"vue-3-version/guide/components/polygon",
				"vue-3-version/guide/components/polyline",
				"vue-3-version/guide/components/rectangle",
				"vue-3-version/guide/components/autocomplete",
				"vue-3-version/guide/components/other-components",
			],
		},
		{
			type: "category",
			label: "API reference",
			collapsed: true,
			items: [
				"vue-3-version/api/main.ts",
				"vue-3-version/api/gmap-vue-plugin",
				"vue-3-version/api/components/introduction",
				"vue-3-version/api/components/map",
				"vue-3-version/api/components/marker",
				"vue-3-version/api/components/info-window",
				"vue-3-version/api/components/circle",
				"vue-3-version/api/components/polygon",
				"vue-3-version/api/components/polyline",
				"vue-3-version/api/components/rectangle",
				"vue-3-version/api/components/autocomplete",
				"vue-3-version/api/composables",
				"vue-3-version/api/utilities",
				"vue-3-version/api/types",
			],
		},
		{
			type: "category",
			label: "Project",
			collapsed: true,
			items: [
				"vue-3-version/changelog/changelog",
				"vue-3-version/developers/README",
				"vue-3-version/developers/test-the-plugin",
				"vue-3-version/developers/license",
			],
		},
	],
	vue2Version: [{ type: "autogenerated", dirName: "vue-2-version" }],
};

export default sidebars;
