name: documentation
on:
  push:
    branches:
      - master

jobs:
  publish:
    name: github pages
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install pnpm
        run: npm install --location=global pnpm@9.0.6
      - name: Remove pnpm-workspace.yaml
        run: rm -rf ./pnpm-workspace.yaml
      - name: Install dependencies
        working-directory: ./packages/documentation
        run: pnpm install
      - name: Build docs
        working-directory: ./packages/documentation
        run: pnpm run build
      - name: GitHub Pages
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: gh-pages
          build_dir: ./packages/documentation/build
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN_REPO }}
