name: documentation
on:
  push:
    branches:
      - master

jobs:
  publish:

    name: github pages
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Install pnpm
        run: npm install -g pnpm
      - name: Install dependencies
        working-directory: ./packages/documentation
        run: pnpm install
      - name: Install Webpack 4
        working-directory: ./packages/documentation
        run: pnpm add --save webpack@4.0.0
      - name: Build docs
        working-directory: ./packages/documentation
        run: pnpm run build:docs
      - name: GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.2
        with:
          target_branch: gh-pages
          build_dir: ./packages/documentation/docs/.vuepress/dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
